2021-01-11 11:24:35,853 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [4871]
2021-01-11 11:24:35,859 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 11:24:35,861 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 11:27:36,747 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 11:27:36,851 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 11:27:36,868 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 11:27:36,873 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [4871]
2021-01-11 11:27:39,848 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [5215]
2021-01-11 11:27:39,851 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 11:27:39,854 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 11:40:26,222 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 11:40:26,327 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 11:40:26,332 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 11:40:26,336 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [5215]
2021-01-11 12:00:01,952 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [1516]
2021-01-11 12:00:01,954 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:00:01,956 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:00:09,566 loglevel=INFO   logger=main log_request() L68   rid=6f54cbf6-0cbf-4d37-a64f-39fc77594a55 start request path=/docs
2021-01-11 12:00:10,387 loglevel=INFO   logger=main log_request() L68   rid=d63f07fd-0756-4767-a2e4-955eed1e8d60 start request path=/openapi.json
2021-01-11 12:00:12,102 loglevel=INFO   logger=main log_request() L68   rid=b755e3c3-fda9-465d-bf05-112ad47bb1bc start request path=/[object Module]
2021-01-11 12:00:18,482 loglevel=INFO   logger=main log_request() L68   rid=e9ec357b-5c35-4390-a3db-72817f71032b start request path=/get_jwt
2021-01-11 12:00:32,349 loglevel=INFO   logger=main log_request() L68   rid=796b0a1b-d5ab-41ae-bb64-b5d8e3b7ac32 start request path=/[object Module]
2021-01-11 12:00:38,648 loglevel=INFO   logger=main log_request() L68   rid=419a279e-3d0f-439d-84c7-f67b4439f17c start request path=/request_token
2021-01-11 12:00:38,652 loglevel=INFO   logger=v1.routers.oauth request_access_token() L56   RequestId: 419a279e-3d0f-439d-84c7-f67b4439f17c, Path requested: /request_token, body: {"grant_type": "urn:ietf:params:oauth:grant-type:jwt-bearer", "assertion": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJHbG9iZU9TUyIsImF1ZCI6Imh0dHA6Ly9hcGlzZXJ2ZXIvYXBpL29hdXRoL3Rva2VuIiwiZXhwIjoxNjEwMzM5NDE4LCJpYXQiOjE2MTAzMzc2MTh9.poYBBiaq4iA7uUzg1lt1JG6-lP4CndZOa_LE2nL9rCawmgEr8nBSoeupGtSUR-1eAxAvltDUW6dSq8jSFxj_dDtalv4VMNppgIU56_DV-uLbpyucKKVesLQpHQILALN-XsVBmf5wqwimPBwLaj_QpFtDryu5o-M8iktPwNpe4-OD6mK1QEkNU77qc2dpuGbWXPAfBZ4VkRb6CXegvjE7h_kKbd9cttwmLBVP7X2IjemLAweAXyY3-B9rRkAAiA1GPlAedUbMCAwPZ5TI4mNhUflkCu3vdu2idC1ZFulN7beusGmLkVfo1T18QqbXNOXnLSbO0fd_foqy2bRPC7Ar_A"}
2021-01-11 12:00:47,276 loglevel=INFO   logger=main log_request() L68   rid=018be9e6-a0c5-4e67-9add-d2256cdf8404 start request path=/[object Module]
2021-01-11 12:00:54,276 loglevel=INFO   logger=main log_request() L68   rid=65dea277-d244-4874-b41c-059687353fc7 start request path=/validate_access_token
2021-01-11 12:00:54,280 loglevel=INFO   logger=v1.routers.oauth validate_access_token() L127  RequestId: 65dea277-d244-4874-b41c-059687353fc7, Path requested: /validate_access_token, body: {"access_token": "k_4RRFAMZjh1epWZAnSFO8x3UxLKZg"}
2021-01-11 12:00:58,628 loglevel=INFO   logger=main log_request() L68   rid=a03470f7-4d9e-4cd6-bde7-a0ee672edc35 start request path=/[object Module]
2021-01-11 12:01:05,465 loglevel=INFO   logger=main log_request() L68   rid=99eb84d4-5a6b-4200-a42a-7d828a64b901 start request path=/refresh_token
2021-01-11 12:01:05,467 loglevel=INFO   logger=v1.routers.oauth refresh_token() L83   RequestId: 99eb84d4-5a6b-4200-a42a-7d828a64b901, Path requested: /refresh_token, body: {"refresh_token": "k_4RRFAMZjh1epWZAnSFO8x3UxLKZgg"}
2021-01-11 12:01:05,472 loglevel=ERROR  logger=v1.routers.oauth refresh_token() L95   RequestId: 99eb84d4-5a6b-4200-a42a-7d828a64b901, Msg: Refresh Token Invalid.
2021-01-11 12:02:02,200 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:02:02,304 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:02:02,307 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:02:02,309 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [1516]
2021-01-11 12:02:04,967 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [1721]
2021-01-11 12:02:04,970 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:02:04,973 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:02:37,955 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:02:38,057 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:02:38,059 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:02:38,061 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [1721]
2021-01-11 12:02:40,658 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [1788]
2021-01-11 12:02:40,662 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:02:40,665 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:02:49,446 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:02:49,549 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:02:49,552 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:02:49,555 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [1788]
2021-01-11 12:02:51,921 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [1817]
2021-01-11 12:02:51,923 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:02:51,926 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:07:11,217 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:07:11,320 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:07:11,323 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:07:11,325 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [1817]
2021-01-11 12:07:13,896 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [2324]
2021-01-11 12:07:13,899 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:07:13,901 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:09:00,019 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:09:00,123 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:09:00,127 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:09:00,129 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [2324]
2021-01-11 12:09:02,837 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [2528]
2021-01-11 12:09:02,842 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:09:02,844 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:10:19,363 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:10:19,466 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:10:19,468 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:10:19,471 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [2528]
2021-01-11 12:10:22,009 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [2682]
2021-01-11 12:10:22,013 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:10:22,017 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:11:16,114 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:11:16,248 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:11:16,323 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:11:16,325 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [2682]
2021-01-11 12:11:19,251 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [2789]
2021-01-11 12:11:19,254 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:11:19,256 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:13:06,747 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:13:06,850 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:13:06,853 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:13:06,856 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [2789]
2021-01-11 12:13:09,898 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [2986]
2021-01-11 12:13:09,900 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:13:09,904 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:13:21,492 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:13:21,595 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:13:21,597 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:13:21,600 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [2986]
2021-01-11 12:13:24,271 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [3022]
2021-01-11 12:13:24,274 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:13:24,275 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:13:41,546 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:13:41,648 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:13:41,650 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:13:41,650 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [3022]
2021-01-11 12:13:44,468 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [3061]
2021-01-11 12:13:44,472 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:13:44,474 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:13:56,782 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:13:56,885 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:13:56,889 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:13:56,892 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [3061]
2021-01-11 12:14:00,074 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [3103]
2021-01-11 12:14:00,077 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:14:00,078 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:14:04,191 loglevel=INFO   logger=main log_request() L86   rid=a7f1c056-97d5-406a-b91a-71835e98edce start request path=/get_jwt
2021-01-11 12:14:21,355 loglevel=INFO   logger=main log_request() L86   rid=d94adf2c-879f-4058-86bb-8f529c8c2d08 start request path=/request_token
2021-01-11 12:14:21,357 loglevel=INFO   logger=v1.routers.oauth request_access_token() L56   RequestId: d94adf2c-879f-4058-86bb-8f529c8c2d08, Path requested: /request_token, body: {"grant_type": "urn:ietf:params:oauth:grant-type:jwt-bearer", "assertion": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJHbG9iZVMiLCJhdWQiOiJodHRwOi8vYXBpc2VydmVyL2FwaS9vYXV0aC90b2tlbiIsImV4cCI6MTYxMDM0MDI0NCwiaWF0IjoxNjEwMzM4NDQ0fQ.XKxPeSBREEcTozgFg_Zg1Lmp3DkXMNxqbqs65gl6FNXMrAh4rCuBsGkFmTj_cLd2uXowUziSprK-YVXnXwKRPe40jFMQdqCVXQb3BSZDYTdCfK3Y4XT7hZYb9l1eAn1QizBnchvKbxpEKge-SQRalsYvPla7TCT4fAf5az3Nbgkq0wXzYpZGqNkDI5uAux_cJn_sFS0Ol8xD-rMkeVuRi3CUD-eNE3KCafag8uyD8jWBslDX1iW14LXaEwOCG3dyqZhBfSzoRH_614APVF0h3nwdW4JvJcdemGJ2Dmojf1yfPmsKukeIBBmvSirVBR6AKTCy06SrwsZpSSxHtBKLrw"}
2021-01-11 12:14:41,768 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:14:41,869 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:14:41,871 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:14:41,873 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [3103]
2021-01-11 12:14:44,814 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [3193]
2021-01-11 12:14:44,819 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:14:44,825 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:15:29,108 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:15:29,210 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:15:29,213 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:15:29,216 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [3193]
2021-01-11 12:16:53,769 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [3487]
2021-01-11 12:16:53,771 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:16:53,773 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:16:53,777 loglevel=INFO   logger=main log_request() L87   rid=5f7a4c20-950f-4a5e-97b6-c3af76011038 start request path=/docs
2021-01-11 12:16:53,778 loglevel=INFO   logger=main log_request() L87   rid=5acd7e89-f466-4111-96e7-787014bc67d4 start request path=/docs
2021-01-11 12:16:54,315 loglevel=INFO   logger=main log_request() L87   rid=ad15315b-f549-4fe2-b7da-172370fef1cc start request path=/openapi.json
2021-01-11 12:16:56,522 loglevel=INFO   logger=main log_request() L87   rid=fbf81ffd-f0e1-4fca-8f07-6e0fb9c9c1cd start request path=/docs
2021-01-11 12:16:56,737 loglevel=INFO   logger=main log_request() L87   rid=fc2ba7b3-23f2-42d3-b231-04c3d8284caa start request path=/openapi.json
2021-01-11 12:16:58,457 loglevel=INFO   logger=main log_request() L87   rid=736c0eef-4e20-4947-97e5-fbef5421f608 start request path=/[object Module]
2021-01-11 12:17:02,762 loglevel=INFO   logger=main log_request() L87   rid=5d22a9f4-4408-4c1c-93e1-294a16bbf088 start request path=/basic_auth
2021-01-11 12:22:15,231 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:22:15,334 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:22:15,337 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:22:15,339 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [3487]
2021-01-11 12:22:17,838 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [4119]
2021-01-11 12:22:17,841 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:22:17,844 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:22:59,694 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:22:59,797 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:22:59,800 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:22:59,802 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [4119]
2021-01-11 12:23:02,493 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [4214]
2021-01-11 12:23:02,497 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:23:02,500 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:24:00,487 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:24:00,590 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:24:00,594 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:24:00,598 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [4214]
2021-01-11 12:24:03,381 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [4330]
2021-01-11 12:24:03,385 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:24:03,388 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:24:47,577 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:24:47,679 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:24:47,683 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:24:47,686 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [4330]
2021-01-11 12:24:50,408 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [4424]
2021-01-11 12:24:50,411 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:24:50,414 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:26:09,412 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:26:09,515 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:26:09,518 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:26:09,521 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [4424]
2021-01-11 12:26:23,907 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [4615]
2021-01-11 12:26:23,910 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:26:23,913 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:28:05,204 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:28:05,307 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:28:05,310 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:28:05,312 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [4615]
2021-01-11 12:28:07,843 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [4825]
2021-01-11 12:28:07,845 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:28:07,848 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:28:27,806 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:28:27,909 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:28:27,911 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:28:27,914 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [4825]
2021-01-11 12:28:30,805 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [4885]
2021-01-11 12:28:30,809 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:28:30,811 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:30:57,520 loglevel=INFO   logger=main log_request() L105  rid=f030198c-9354-4ec0-bd4b-5ceb227fedab start request path=/basic_auth
2021-01-11 12:30:57,531 loglevel=ERROR  logger=uvicorn.error run_asgi() L397  Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/applications.py", line 201, in __call__
    await super().__call__(scope, receive, send)  # pragma: no cover
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "./main.py", line 106, in log_request
    response = await call_next(request)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/routing.py", line 202, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./v1/routers/basic_auth.py", line 18, in basic_auth_verification
    result = basicAuthentication.validate_basic_auth(form_data.username, form_data.password)
  File "./v1/services/basic_auth.py", line 20, in validate_basic_auth
    except NoResultFound:
NameError: name 'NoResultFound' is not defined
2021-01-11 12:31:51,531 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:31:51,634 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:31:51,635 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:31:51,636 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [4885]
2021-01-11 12:31:54,372 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [5263]
2021-01-11 12:31:54,375 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:31:54,376 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:31:56,956 loglevel=INFO   logger=main log_request() L105  rid=d73297a0-5702-4328-ac7d-021e5f6796ef start request path=/basic_auth
2021-01-11 12:31:56,965 loglevel=ERROR  logger=uvicorn.error run_asgi() L397  Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/applications.py", line 201, in __call__
    await super().__call__(scope, receive, send)  # pragma: no cover
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "./main.py", line 106, in log_request
    response = await call_next(request)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/routing.py", line 202, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./v1/routers/basic_auth.py", line 20, in basic_auth_verification
    result = basicAuthentication.validate_basic_auth(form_data.username, form_data.password)
  File "./v1/services/basic_auth.py", line 20, in validate_basic_auth
    except NoResultFound:
NameError: name 'NoResultFound' is not defined
2021-01-11 12:32:10,083 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:32:10,187 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:32:10,188 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:32:10,189 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [5263]
2021-01-11 12:32:13,139 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [5304]
2021-01-11 12:32:13,142 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:32:13,144 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:32:14,960 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:32:15,065 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:32:15,068 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:32:15,071 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [5304]
2021-01-11 12:32:17,835 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [5333]
2021-01-11 12:32:17,838 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:32:17,840 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:32:20,638 loglevel=INFO   logger=main log_request() L105  rid=05e7147a-a4ec-4b9e-8b3d-1f49d0164e0e start request path=/basic_auth
2021-01-11 12:32:20,650 loglevel=ERROR  logger=uvicorn.error run_asgi() L397  Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/applications.py", line 201, in __call__
    await super().__call__(scope, receive, send)  # pragma: no cover
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "./main.py", line 106, in log_request
    response = await call_next(request)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/routing.py", line 202, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./v1/routers/basic_auth.py", line 18, in basic_auth_verification
    result = basicAuthentication.validate_basic_auth(form_data.username, form_data.password)
  File "./v1/services/basic_auth.py", line 15, in validate_basic_auth
    user = self.sessiondb.query(UserInformation).filter(
AttributeError: 'BasicAuthentication' object has no attribute 'sessiondb'
2021-01-11 12:33:30,907 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:33:31,010 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:33:31,012 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:33:31,013 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [5333]
2021-01-11 12:33:38,460 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [5491]
2021-01-11 12:33:38,463 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:33:38,466 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:33:45,811 loglevel=INFO   logger=main log_request() L105  rid=d8c95cfc-6e92-4f7b-bd38-f92d0eb0d15a start request path=/basic_auth
2021-01-11 12:33:45,822 loglevel=ERROR  logger=uvicorn.error run_asgi() L397  Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/applications.py", line 201, in __call__
    await super().__call__(scope, receive, send)  # pragma: no cover
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "./main.py", line 106, in log_request
    response = await call_next(request)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/routing.py", line 202, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./v1/routers/basic_auth.py", line 18, in basic_auth_verification
    result = basicAuthentication.validate_basic_auth(form_data.username, form_data.password)
  File "./v1/services/basic_auth.py", line 15, in validate_basic_auth
    user = self.sessiondb.query(UserInformation).filter(
AttributeError: 'BasicAuthentication' object has no attribute 'sessiondb'
2021-01-11 12:36:27,226 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:36:27,328 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:36:27,331 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:36:27,333 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [5491]
2021-01-11 12:36:29,905 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [5845]
2021-01-11 12:36:29,908 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:36:29,911 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:36:43,424 loglevel=INFO   logger=main log_request() L105  rid=163cbd01-a988-4497-8dc2-41951a1eb9f5 start request path=/basic_auth
2021-01-11 12:36:43,435 loglevel=ERROR  logger=uvicorn.error run_asgi() L397  Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/applications.py", line 201, in __call__
    await super().__call__(scope, receive, send)  # pragma: no cover
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "./main.py", line 106, in log_request
    response = await call_next(request)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/routing.py", line 202, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./v1/routers/basic_auth.py", line 18, in basic_auth_verification
    result = basicAuthentication.validate_basic_auth(form_data.username, form_data.password)
  File "./v1/services/basic_auth.py", line 15, in validate_basic_auth
    user = self.sessiondb.query(UserInformation).filter(
AttributeError: 'BasicAuthentication' object has no attribute 'sessiondb'
2021-01-11 12:37:54,083 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:37:54,186 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:37:54,189 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:37:54,192 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [5845]
2021-01-11 12:37:56,655 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [6029]
2021-01-11 12:37:56,658 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:37:56,661 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:38:16,534 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:38:16,637 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:38:16,639 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:38:16,641 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [6029]
2021-01-11 12:38:19,303 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [6080]
2021-01-11 12:38:19,306 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:38:19,309 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:38:20,833 loglevel=INFO   logger=main log_request() L105  rid=ebdfdfab-6d0a-4e4f-89be-cd8c224836fb start request path=/basic_auth
2021-01-11 12:38:20,844 loglevel=ERROR  logger=uvicorn.error run_asgi() L397  Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/applications.py", line 201, in __call__
    await super().__call__(scope, receive, send)  # pragma: no cover
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "./main.py", line 106, in log_request
    response = await call_next(request)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/routing.py", line 202, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./v1/routers/basic_auth.py", line 18, in basic_auth_verification
    result = basicAuthentication.validate_basic_auth(form_data.username, form_data.password)
  File "./v1/services/basic_auth.py", line 15, in validate_basic_auth
    user = self.dbsession.query(UserInformation).filter(
AttributeError: 'BasicAuthentication' object has no attribute 'dbsession'
2021-01-11 12:38:43,660 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:38:43,763 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:38:43,766 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:38:43,768 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [6080]
2021-01-11 12:38:46,527 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [6141]
2021-01-11 12:38:46,530 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:38:46,532 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:39:36,734 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:39:36,839 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:39:36,841 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:39:36,842 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [6141]
2021-01-11 12:39:39,532 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [6261]
2021-01-11 12:39:39,534 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:39:39,537 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:40:12,121 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:40:12,224 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:40:12,227 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:40:12,229 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [6261]
2021-01-11 12:40:15,026 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [6331]
2021-01-11 12:40:15,029 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:40:15,032 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:40:19,637 loglevel=INFO   logger=main log_request() L105  rid=1f516b10-b4af-44ce-87c0-87f6a9643fdc start request path=/basic_auth
2021-01-11 12:40:19,650 loglevel=ERROR  logger=uvicorn.error run_asgi() L397  Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/applications.py", line 201, in __call__
    await super().__call__(scope, receive, send)  # pragma: no cover
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "./main.py", line 106, in log_request
    response = await call_next(request)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/routing.py", line 202, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./v1/routers/basic_auth.py", line 22, in basic_auth_verification
    return JSONResponse(
NameError: name 'JSONResponse' is not defined
2021-01-11 12:40:30,391 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:40:30,496 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:40:30,498 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:40:30,500 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [6331]
2021-01-11 12:40:32,963 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [6396]
2021-01-11 12:40:32,966 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:40:32,969 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:40:35,170 loglevel=INFO   logger=main log_request() L105  rid=ff04a1d2-3e1a-48f1-ac23-23ffc94f0afa start request path=/basic_auth
2021-01-11 12:40:35,180 loglevel=ERROR  logger=uvicorn.error run_asgi() L397  Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/applications.py", line 201, in __call__
    await super().__call__(scope, receive, send)  # pragma: no cover
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "./main.py", line 106, in log_request
    response = await call_next(request)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/routing.py", line 202, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./v1/routers/basic_auth.py", line 22, in basic_auth_verification
    return JSONResponse(
NameError: name 'JSONResponse' is not defined
2021-01-11 12:41:03,793 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:41:03,898 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:41:03,900 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:41:03,902 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [6396]
2021-01-11 12:41:06,387 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [6473]
2021-01-11 12:41:06,390 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:41:06,393 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:41:10,655 loglevel=INFO   logger=main log_request() L105  rid=7dc1fa32-3ba8-4c65-b12b-d84286ef7723 start request path=/basic_auth
2021-01-11 12:41:10,665 loglevel=ERROR  logger=uvicorn.error run_asgi() L397  Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/applications.py", line 201, in __call__
    await super().__call__(scope, receive, send)  # pragma: no cover
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "./main.py", line 106, in log_request
    response = await call_next(request)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/routing.py", line 202, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./v1/routers/basic_auth.py", line 26, in basic_auth_verification
    "requestId": f"{requestId}",
NameError: name 'requestId' is not defined
2021-01-11 12:41:56,996 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:41:57,101 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:41:57,103 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:41:57,105 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [6473]
2021-01-11 12:41:59,784 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [6563]
2021-01-11 12:41:59,793 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:41:59,797 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:42:00,489 loglevel=INFO   logger=main log_request() L105  rid=25ec2ef3-a093-4ff7-af1b-0f60b43687d4 start request path=/basic_auth
2021-01-11 12:42:18,067 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:42:18,172 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:42:18,175 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:42:18,177 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [6563]
2021-01-11 12:42:20,735 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [6609]
2021-01-11 12:42:20,738 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:42:20,741 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:42:20,747 loglevel=INFO   logger=main log_request() L105  rid=a0cfd52d-a61d-404e-a103-62042ecc7c0d start request path=/basic_auth
2021-01-11 12:42:20,753 loglevel=ERROR  logger=uvicorn.error run_asgi() L397  Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/applications.py", line 201, in __call__
    await super().__call__(scope, receive, send)  # pragma: no cover
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "./main.py", line 106, in log_request
    response = await call_next(request)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/routing.py", line 202, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./v1/routers/basic_auth.py", line 20, in basic_auth_verification
    result = basicAuthentication.validate_basic_auth(form_data.username, form_data.password)
  File "./v1/services/basic_auth.py", line 14, in validate_basic_auth
    print(self.sessiondb)
AttributeError: 'BasicAuthentication' object has no attribute 'sessiondb'
2021-01-11 12:42:38,586 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:42:38,696 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:42:38,712 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:42:38,724 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [6609]
2021-01-11 12:42:41,242 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [6648]
2021-01-11 12:42:41,245 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:42:41,249 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:42:41,939 loglevel=INFO   logger=main log_request() L105  rid=9caaabe7-7ce4-498e-bf23-8fe5ba4a707d start request path=/basic_auth
2021-01-11 12:42:41,944 loglevel=ERROR  logger=uvicorn.error run_asgi() L397  Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/applications.py", line 201, in __call__
    await super().__call__(scope, receive, send)  # pragma: no cover
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "./main.py", line 106, in log_request
    response = await call_next(request)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/routing.py", line 202, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/mnt/c/Users/Kar Ming/Desktop/ubuntu/Project_Code/DST_BI/dst_auth/venv/lib/python3.6/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./v1/routers/basic_auth.py", line 20, in basic_auth_verification
    result = basicAuthentication.validate_basic_auth(form_data.username, form_data.password)
  File "./v1/services/basic_auth.py", line 14, in validate_basic_auth
    print(self.sessiondb)
AttributeError: 'BasicAuthentication' object has no attribute 'sessiondb'
2021-01-11 12:42:53,974 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:42:54,078 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:42:54,081 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:42:54,084 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [6648]
2021-01-11 12:42:56,638 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [6686]
2021-01-11 12:42:56,640 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:42:56,643 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:43:04,224 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:43:04,327 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:43:04,330 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:43:04,332 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [6686]
2021-01-11 12:43:06,947 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [6710]
2021-01-11 12:43:06,950 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:43:06,953 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:43:07,279 loglevel=INFO   logger=main log_request() L105  rid=47a340ce-335d-4db7-b76b-8905878931c5 start request path=/basic_auth
2021-01-11 12:43:13,186 loglevel=INFO   logger=main log_request() L105  rid=575edb26-0822-4fad-8f2c-41672d3b679f start request path=/basic_auth
2021-01-11 12:43:46,428 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:43:46,538 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:43:46,579 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:43:46,593 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [6710]
2021-01-11 12:43:49,210 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [6815]
2021-01-11 12:43:49,213 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:43:49,215 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:44:11,614 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:44:11,718 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:44:11,720 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:44:11,722 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [6815]
2021-01-11 12:44:14,408 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [6868]
2021-01-11 12:44:14,411 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:44:14,413 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:44:22,435 loglevel=INFO   logger=main log_request() L105  rid=423d6fbd-6071-4b37-a5b6-2269e7da4f25 start request path=/basic_auth
2021-01-11 12:45:52,764 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:45:52,868 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:45:52,870 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:45:52,873 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [6868]
2021-01-11 12:45:56,139 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [7039]
2021-01-11 12:45:56,144 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:45:56,147 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:45:56,154 loglevel=INFO   logger=main log_request() L105  rid=8e405fb2-5705-457a-ba1b-e4816e05ed59 start request path=/docs
2021-01-11 12:45:56,513 loglevel=INFO   logger=main log_request() L105  rid=08794c56-7c2f-4707-a1c9-db8add8b64a7 start request path=/openapi.json
2021-01-11 12:46:16,228 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:46:16,331 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:46:16,334 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:46:16,336 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [7039]
2021-01-11 12:46:18,991 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [7099]
2021-01-11 12:46:18,993 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:46:18,996 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:46:22,121 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 12:46:22,224 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 12:46:22,227 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 12:46:22,229 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [7099]
2021-01-11 12:46:24,782 loglevel=INFO   logger=uvicorn.error serve() L63   Started server process [7127]
2021-01-11 12:46:24,788 loglevel=INFO   logger=uvicorn.error startup() L26   Waiting for application startup.
2021-01-11 12:46:24,793 loglevel=INFO   logger=uvicorn.error startup() L38   Application startup complete.
2021-01-11 12:46:24,808 loglevel=INFO   logger=main log_request() L105  rid=23ad1c50-25ae-4990-9070-75834834a1b2 start request path=/docs
2021-01-11 12:46:25,231 loglevel=INFO   logger=main log_request() L105  rid=cf480f43-71d2-48ab-8531-8011f38705f0 start request path=/openapi.json
2021-01-11 12:47:02,581 loglevel=INFO   logger=main log_request() L105  rid=e4e5a73b-a183-4ddc-8073-25d49a3d201a start request path=/[object Module]
2021-01-11 13:14:02,682 loglevel=INFO   logger=uvicorn.error shutdown() L209  Shutting down
2021-01-11 13:14:02,788 loglevel=INFO   logger=uvicorn.error shutdown() L43   Waiting for application shutdown.
2021-01-11 13:14:02,792 loglevel=INFO   logger=uvicorn.error shutdown() L46   Application shutdown complete.
2021-01-11 13:14:02,795 loglevel=INFO   logger=uvicorn.error serve() L76   Finished server process [7127]
